### ISSUE TITLE
How can Request support @Transactional?

### ISSUE THREAD

**Issue by zhangxun165** [assertj/assertj-db#68]
when I use `@Transactional` and `@Rollback` on a test，why the Request get an unexpected value?

``` java
@Test
@Transactional
@Rollback
public void test_insert_sys_record(){
    // prepare SysInfoDO

    // insert one record into database
    sysDao.insertSysInfo(sysInfoDO);

    String querySQL = "select count(1) from my_sys_table";
    JdbcTemplate jt = new JdbcTemplate(dataSource);
    // get the expected value-1
    jt.queryForObject(querySQL, Integer.class);

    Request request = new Request(dataSource, querySQL);
    // get the unexpected value-0, why?
    request.getRow(0).getColumnValue(0).getValue();
}
```

**Comment by VanRoy** [comment]
Hi @zhangxun165 , it's because JdbcTemplate is aware of @Transactional but AssertJ-DB not.
Indeed AssertJ-DB is designed for working with his own DB connection to validate the "real"  status of the database.
Maybe you can bypass that to set default Isolation level of your datasource to READ_UNCOMMITTED

**Comment by VanRoy** [comment]
@zhangxun165 Can you provide us an update for this issue ?

**Comment by VanRoy** [comment]
Hi @zhangxun165 , I think you can solve this issue with use of `TransactionAwareDataSourceProxy` from spring-tx

`
Request request = new Request(TransactionAwareDataSourceProxy(dataSource), querySQL);
`
